project_id = "bupbucfdisqedteazifs"

[functions.create-order]
verify_jwt = true

[functions.send-security-alert]
verify_jwt = true

[functions.verify-recaptcha]
verify_jwt = false

[functions.check-device-trust]
verify_jwt = true