project_id = "bupbucfdisqedteazifs"

[functions.create-order]
verify_jwt = true

[functions.audit-log]
verify_jwt = false

[functions.detect-anomalies]
verify_jwt = true

[functions.send-security-alert]
verify_jwt = false
